name: Databricks Bundle Deploy - dev

on:
  push:
    branches:
      - features/added_notebook2
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@v0.269.0   # ✅ latest stable release

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Debug Databricks CLI version
        run: databricks --version

      - name: Deploy Databricks bundle
        run: databricks bundle deploy --auto-approve
